version: "3.4"
services:
  db:
    build:
      context: ./docker/db
      dockerfile: ./Dockerfile
    environment:
      SA_PASSWORD: YourStrong!Passw0rd
      ACCEPT_EULA: Y
    ports:
      - "1433:1433"
    healthcheck:
      test: sqlcmd -S localhost -U sa -P 'YourStrong!Passw0rd' -Q 'select 1'
      interval: 30s
      timeout: 10s
      retries: 5

  amqp:
    build:
      context: ./docker/amqp
      dockerfile: ./Dockerfile
    ports:
      - "5672:5672"
      - "61616:61616"
      - "8161:8161"

  seed:
    build:
      context: .
      dockerfile: ./docker/seed/Dockerfile
    ports:
      - "5000:5000"
      - "7000:7000"
    environment:
      ASPNETCORE_URLS: "http://*:5000"
    depends_on:
      - db
      - amqp

  node:
    build:
      context: .
      dockerfile: ./docker/node/Dockerfile
    ports:
      - "5001:5000"
      - "7001:7001"
    environment:
      ASPNETCORE_URLS: "http://*:5000"
    depends_on:
      - db
      - amqp
      - seed
