version: "3.4"
services:

  graphite:
    image: hopsoft/graphite-statsd
    restart: always
    ports:
      - "8090:80"
      - "8091:81"
      - "2003-2004:2003-2004"
      - "2023-2024:2023-2024"
      - "8125:8125/udp"
      - "8126:8126"

  db:
    build:
      context: ./docker/db
      dockerfile: ./Dockerfile
    environment:
      SA_PASSWORD: YourStrong!Passw0rd
      ACCEPT_EULA: Y
    ports:
      - "1433:1433"
    healthcheck:
      test: sqlcmd -S localhost -U sa -P 'YourStrong!Passw0rd' -Q 'select 1'
      interval: 30s
      timeout: 10s
      retries: 5

  amqp:
    build:
      context: ./docker/amqp
      dockerfile: ./Dockerfile
    ports:
      - "5672:5672"
      - "61616:61616"
      - "8161:8161"
    healthcheck:
      test: curl -f http://amqp:8161 || false

  seed:
    build:
      context: .
      dockerfile: ./docker/seed/Dockerfile
    ports:
      - "5000:5000"
      - "7000:7000"
    environment:
      ASPNETCORE_URLS: "http://*:5000"
    healthcheck:
      test: wget -q --spider -P /dev/null http://seed:5000/api/hello/world
    restart: always
    depends_on:
      - db
      - amqp

  node:
    build:
      context: .
      dockerfile: ./docker/node/Dockerfile
    ports:
      - "5001:5000"
      - "7001:7001"
    environment:
      ASPNETCORE_URLS: "http://*:5000"
    healthcheck:
      test: wget -q --spider -P /dev/null http://node:5000/api/hello/world
    restart: always
    depends_on:
      - db
      - amqp
      - seed
