version: 2
jobs:
  build:
    docker:
      - image: mcr.microsoft.com/dotnet/core/sdk:2.1
    steps:
      - checkout
      - run: find .
      - run: dotnet restore
      - run: dotnet build
      - run: dotnet pack src/wyvern.api/wyvern.api.csproj
      - run: dotnet nuget push src/wyvern.api/bin/Debug/wyvern.api.1.0.0.nupkg --api-key $nuget_api_key --source https://api.nuget.org/v3/index.json
