version: 2
jobs:
  build:
    branches:
      only:
        # - master
        - v2.0
    docker:
      - image: mcr.microsoft.com/dotnet/core/sdk:2.2.204
    steps:
      - checkout
      - run: dotnet build
      - run: dotnet test --no-build --logger "trx"
      - run:
          name: test results
          command: |
            dotnet tool install -g trx2junit
            export PATH="$PATH:/root/.dotnet/tools"
            trx2junit src/wyvern.api.tests/TestResults/*.trx --output TestResults/wyvern.api.tests/
            trx2junit src/wyvern.utils.tests/TestResults/*.trx --output TestResults/wyvern.utils.tests/
      - store_test_results:
          path: TestResults
      - store_artifacts:
          path: TestResults
          destination: TestResults
      - run:
          name: pack
          command: |
            dotnet pack --no-build src/wyvern.visualize/wyvern.visualize.csproj /p:Version=2.0.$CIRCLE_BUILD_NUM-alpha --include-symbols -p:SymbolPackageFormat=snupkg --include-source
            dotnet pack --no-build src/wyvern.utils/wyvern.utils.csproj /p:Version=2.0.$CIRCLE_BUILD_NUM-alpha --include-symbols -p:SymbolPackageFormat=snupkg --include-source
            dotnet pack --no-build src/wyvern.entity/wyvern.entity.csproj /p:Version=2.0.$CIRCLE_BUILD_NUM-alpha --include-symbols -p:SymbolPackageFormat=snupkg --include-source
            dotnet pack --no-build src/wyvern.api/wyvern.api.csproj /p:Version=2.0.$CIRCLE_BUILD_NUM-alpha --include-symbols -p:SymbolPackageFormat=snupkg --include-source
            dotnet pack --no-build src/wyvern.monitoring.statsd/wyvern.monitoring.statsd.csproj /p:Version=2.0.$CIRCLE_BUILD_NUM-alpha --include-symbols -p:SymbolPackageFormat=snupkg --include-source
            dotnet pack --no-build src/wyvern.monitoring/wyvern.monitoring.csproj /p:Version=2.0.$CIRCLE_BUILD_NUM-alpha --include-symbols -p:SymbolPackageFormat=snupkg --include-source
      - run:
          name: push
          command: |
            dotnet nuget push src/wyvern.visualize/bin/Debug/wyvern.visualize.2.0.$CIRCLE_BUILD_NUM-alpha.nupkg --api-key $nuget_api_key --source https://api.nuget.org/v3/index.json
            dotnet nuget push src/wyvern.utils/bin/Debug/wyvern.utils.2.0.$CIRCLE_BUILD_NUM-alpha.nupkg --api-key $nuget_api_key --source https://api.nuget.org/v3/index.json
            dotnet nuget push src/wyvern.entity/bin/Debug/wyvern.entity.2.0.$CIRCLE_BUILD_NUM-alpha.nupkg --api-key $nuget_api_key --source https://api.nuget.org/v3/index.json
            dotnet nuget push src/wyvern.api/bin/Debug/wyvern.api.2.0.$CIRCLE_BUILD_NUM-alpha.nupkg --api-key $nuget_api_key --source https://api.nuget.org/v3/index.json
            dotnet nuget push src/wyvern.monitoring.statsd/bin/Debug/wyvern.monitoring.statsd.2.0.$CIRCLE_BUILD_NUM-alpha.nupkg --api-key $nuget_api_key --source https://api.nuget.org/v3/index.json
            dotnet nuget push src/wyvern.monitoring/bin/Debug/wyvern.monitoring.2.0.$CIRCLE_BUILD_NUM-alpha.nupkg --api-key $nuget_api_key --source https://api.nuget.org/v3/index.json
